qualfa2fq.pl
xa2multi.pl

This is useful, e.g. if your perl is not installed in `/usr/bin` or you want to give a specific perl precendence over the one installed in `/usr/bin`. The `-w` is not needed since there is also `use warnings;` in these scripts.

use more portable /usr/bin/env perl for scripts

---

maxk.c

Although installation works for me on OS X El Capitan, installation was failing on Ubuntu 12.04.5 LTS and giving the following warnings/errors:
gcc -c -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS  maxk.c -o maxk.o
maxk.c: In function ‘main_maxk’:
maxk.c:21:2: warning: implicit declaration of function ‘getopt’ [-Wimplicit-function-declaration]
maxk.c:24:6: error: ‘optind’ undeclared (first use in this function)
maxk.c:24:6: note: each undeclared identifier is reported only once for each function it appears in
maxk.c:28:7: warning: left-hand operand of comma expression has no effect [-Wunused-value]
maxk.c:28:7: warning: value computed is not used [-Wunused-value]
maxk.c:28:7: warning: left-hand operand of comma expression has no effect [-Wunused-value]
make: *** …

Include 'unistd.h' to explicitly declare 'getopt'

---

bwakit/run-gen-ref

The link in the file appears to no longer exist.

Editing URL for b38 download

---

bwape.c
bwase.c

it an alignment runs off the end of a chromosome bwa_sa2pos will return without setting strand, which can result in reads being silently reverse complemented

ensure bwa_sa2pos does not return without setting strand

---

bwa.1

MAN page described `bwa mem` option `-D` variously as integer and float,
when it is in fact a float.

Minor doc fix

---

bwtsw2_pair.c

@tillea's issue #108 appears to be caused by there being no sufficiently good pairs when calculating avg and std, leading to avg=NAN std=NAN and a later malloc failure when asked to malloc an insane amount of memory.
This suggested patch returns from `bsw2_stat()` with `r.failed = 1` in this case, as in other cases of insufficient read pairs.  I am not familiar enough with the implications of “failure to infer insert size distribution” to judge whether this is the best approach.

Fail to infer insert size distribution when no pairs are within boundaries (re issue 108)

---

README.md
bntseq.c
bwa.1
bwa.c
bwape.c
bwase.c
bwt_gen.c
bwt_lite.c
bwtaln.c
bwtgap.c
bwtgap.h
bwtindex.c
bwtsw2_pair.c
fastmap.c
kthread.c
malloc_wrap.c

Hi Heng,
To facilitate merging I've collected and tidied up a number of pull requests into one larger PR.  With one exception, these are just build and minor bug fixes and a README cleanup.  For various of the proposed PRs, I've analysed the underlying problem and come up with what I believe is the best fix.
This PR supersedes the following:
* FreeBSD / Alpine Linux build fixes; abs() warnings
Rather than adding more headers so `u_int32_t` can be used, just use the usual `uint32_t` instead. Add explicit casts to the `abs()`/`fabs()`calls — see commit message for reasoning.
Closes #33 (apart from the `CC=cc` change). Closes #68. Closes #90. Closes #130.
* Fix BWTIncFree() memory leak, and add to the previous PR so BWTFree() works properly. Closes #37.
* Change `bns_fasta2bntseq` to only …

Various collected fixes (updated versions of several existing PRs)

---

bwa.c

Resolve issue #83 (Inclusion of literal TAB characters leads to violation of SAM spec)

Forbid literal TAB control characters in @RG line

---

bwa.1

Some of the man page text needed correction, and to include info from the help strings.

Typos, doc improvements in man page

---

bwamem.c

@lh3 
A lot of downstream tools rely upon having a mate cigar present.  To set the mate cigar efficiently, we need to have read pairs grouped together, so it is a bit a pain if the BAM is already coordinate sorted.  Tools like [`SetMateInformation`](http://fulcrumgenomics.github.io/fgbio/tools/latest/SetMateInformation.html) and [`MergeBamAlignment`](https://broadinstitute.github.io/picard/command-line-overview.html#MergeBamAlignment) will add these if not present, but not all folks post-process the output of BWA, and so post-processing is necessary.  Setting the mate cigar _within_ BWA is a better option.
The mate cigar is extremely useful to have, as it allows us to obtain the genomic span of the _template_ rather than just the given end of a read (i.e. R1 or R2), since we can calculate …

Mem should set the mate cigar tag.

---

bwakit/run-bwamem

samtools sort v0.7.15+ requires -o flag to specify the output file

Fix output file parameter for samtools sort

---

bwakit/bwa-postalt.js

This is a really weird one: bwa-postalt will write a corrupt SAM output given SAM input files of very particular size. A reproducing test case is provided here: [bad.sam](https://drive.google.com/open?id=1uBUE1jPVCK9AEdwuQ9Tow2J0qczF5nCu); this file should be of length 1,441,792 bytes with MD5 checksum 33c28ad0404e5ea7923bef9dbdf4af15.
Specifically, if this file is run through bwa-postalt for hs38DH, a corrupt (invalid SAM) last line is output:
```
$ cat bad.sam | /static/tools/bwakit-0.7.15/k8 /static/tools/bwakit-0.7.15/bwa-postalt.js /static/references/genomes/hs38DH/hs38DH.fa.alt | tail -n 3
SRR452464.37604895	99	chr6	169307964	60	25M	=	169308090	151	TTTATTAATTAATAAAATGACCATA	@C@FFFFFHHGHHGHGJJHIJIDHJ	NM:i:0	MD:Z:25	AS:i:25	XS:i:0
SRR452464.37604895	147	chr6	169308090	60	25M	= …
```

Bug/patch: bwa-postalt.js writes invalid output for SAM input that is an exact multiple of 65536 bytes in length

---

rle.h

Hi @lh3,
This PR includes a patch for the upcoming GCC 10, which imports C++'s ODR rule to C too.
I've also fixed the Makefile a bit so we don't have to patch it downstream. `CC` and `AR` don't need to be defined, `make` will use `cc` and `gcc` in their place. By omitting the definition, we don't have to hack the Makefile because we export `CC` and `AR` to the environment, which Make looks for before using the fallbacks.

GCC 10 and Makefile fixes

---

.github/workflows/ci.yaml
.travis.yml

An example GitHub Actions workflow that tests compilation with both GCC and Clang, equivalently to the existing Travis setup. Fixes #324.
After removing _.travis.yml_, I'd recommend going to the bwa repository's [Settings :: Webhooks](https://github.com/lh3/bwa/settings/hooks) page and removing travis's hook; and perhaps also logging in to travis-ci.org and disabling repos and accounts there.

Use GitHub Actions instead of Travis CI

---

bwa.c

In particular, this defines the output SAM to be unsorted BUT also query grouped.  The latter is very important to explicitly define so downstream tools that don't make assumptions know that reads from the same template are grouped.

Add the header line to the output SAM

---

fastmap.c

Clarify that the -5 bwa mem option chooses the alignment that starts earliest in the read relative to the read/sequencing order, not genomic coordinate order

Clarify bwa mem -5 option

---

bwamem_extra.c

Related to https://github.com/lh3/bwa/pull/292 (i.e. the doc for #292 would need to update this).
I would like to know the mapping quality for alternate hits.

Output mapping quality with XB

---

Makefile

Makefile convention is to use CC/CPPFLAGS/CFLAGS/LDFLAGS/LIBS variables in the compile and link rules. This adds `$(CPPFLAGS)` and `$(LDFLAGS)` to the appropriate rules, so that these two can also be used to customise the build in the expected conventional way — in addition to the already present `$(CC)`, `$(CFLAGS)`, and `$(LIBS)`.
In particular, bioconda and Debian would take advantage of these variables in their packaging scripts. Supersedes and closes #247.

Makefile: Use $CPPFLAGS and $LDFLAGS if they are set

---

Makefile
ksw.c
neon_sse.h
scalar_sse.h

Building BWA has long been limited to x86-64 due to the unconditional usage of SSE2 SIMD intrinsics in _ksw.c_'s `ksw_u8()` and `ksw_i16()` functions. This PR adds Neon implementations of these functions, allowing compilation on Aarch64 machines, and also implementations using ordinary scalar C code that at least provide a working (albeit inefficient) build on other (little endian, at least) platforms.
This is done without duplicating the code in _ksw.c_: in most cases, by defining SSE2 intrinsics as `static inline` functions calling Neon intrinsics where there is a direct equivalent; in other cases, by analysing what the SSE2 code is doing semantically and using a non-directly-equivalent Neon intrinsic that has the same effect in the context of the code. (Similarly with the scalar …

Add ARM Neon and scalar implementations of SIMD functions

---

bwamem.c

These were changed to `long` in 9d8c906e4c2de93c240a8d27d59e77c493d17c57 in 2014. Fixes #411.

Fix `kt_for()` declaration parameter types

---

kstring.c
kstring.h

Some people's programs use both HTSlib and libbwa.a — see e.g. samtools/htslib#693. Unfortunately one function — `ksprintf` — is defined in both libraries, leading to linker errors.
This happens for `ksprintf` only, because all the other functions in bwa's _kstring.h_ are declared as `static inline`.
This PR makes `ksprintf()` static inline in _kstring.h_, so that it (like the other _bwa/kstring.h_ functions) won't conflict with similar HTSlib functions. Instead implement it and a new `kvsprintf()` in terms of a new `bwa_kvsprintf()` function. Fixes samtools/htslib#693.

Avoid conflicting with HTSlib's kstring.c functions
